# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default_author.jpg', max_length=255, upload_to='user/avatar/', verbose_name='头像'),
        ),
    ]
