# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-12 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='default_author.jpg', max_length=200, null=True, upload_to='authors/', verbose_name='作者图片'),
        ),
    ]
