# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-12 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='image',
            field=models.ImageField(blank=True, default='default_novel.jpg', max_length=200, null=True, upload_to='novel/', verbose_name='小说图片'),
        ),
    ]
