# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-12 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20181012_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
